### ISSUE TITLE
Ability to fetch data from LibreLinkUp?

### ISSUE THREAD

**Issue by caffe12345** [creepymonster/nightscout-to-libreview#1]
The code looks really amazing. I was trying to extend it to be able to fetch data display it. However here I run into a very long error message bascially saying: "data: { status: 920, reason: 'runningVersionTooLow'}"

Have you got the possibily to add a small piece of code demonstrating how to fetch data from the LibreLinkUp API?

Thanks

**Comment by creepymonster** [comment]
An example code (in JavaScript) is available for example here

https://github.com/timoschlueter/nightscout-librelink-up/blob/main/index.js

Swift code or others are also available.

Many greetings
Reimar
