### ISSUE TITLE
Need Tutorial

### ISSUE THREAD

**Issue by twinko** [creepymonster/nightscout-to-libreview#3]
@creepymonster thank you for you effort. Can you provide a little tutorial, i have no idea how to use your code. Im not a developer but i would love to migrate all my nightscout data (stored at heroku and google cloud) into libreview. I think the data is better to read for my doctor.

**Comment by creepymonster** [comment]
We're having a power outage tonight - I'll try to get you a tutorial up tomorrow night.

A few tools that are really only for developers have to be installed. But I will try to explain that.

Many greetings
Reimar

**Comment by twinko** [comment]
awesome and no rush!

**Comment by creepymonster** [comment]
One question in advance - do you use Windows or MacOS?

**Comment by twinko** [comment]
Hey windows 10. :)

**Comment by creepymonster** [comment]
Hello,

the video is short - I hope it is all good to see.

The URL for the tool is: https://nodejs.org

The commands in the console were (once you are in the nightscout-to-libreview directory):
1. (only before first use): npm Install
2. npm start

**Comment by twinko** [comment]
Hi, there is no video attached :)
oh and maybe add it to the readme, so other who need help like me, find it easily.

**Comment by creepymonster** [comment]
Oops, sorry - here's the link.

https://youtu.be/NEzG2By10B4

**Comment by twinko** [comment]
easy to understand video! Thank you!

**Comment by twinko** [comment]
@creepymonster First of all thank you everything its forking fine.
is it possible to transfer a whole year?
